replicaCount: 1

image:
  tag: 0.1.11

ingress:
  hosts:
    - host: web-app.staging.mycompany.com
      paths: ["/"]

database:
  host: "database-service-staging"
  port: "27017"
  name: "mydatabase"
