replicaCount: 1
host: web-app-service-staging
namespace: staging

image:
  tag: 0.1.34

ingress:
  enabled: true
  hosts:
    - host: web-app-service-staging
      paths: ["/"]

database:
  host: "database-service-staging"
  port: "27017"
  name: "mydatabase"
