replicaCount: 1
host: web-app-service
namespace: staging

image:
  tag: 0.1.37

ingress:
  enabled: true
  hosts:
    - host: database-service
      paths: ["/"]


database:
  host: "database-service"
  port: "27017"
  name: "mydatabase"
