replicaCount: 1

image:
  tag: 0.1.12

ingress:
  enabled: true
  hosts:
    - host: database-service
      paths: ["/"]

database:
  host: "database-service-staging"
  port: "27017"
  name: "mydatabase"
