replicaCount: 1

image:
  repository: docker.io/atakan1927/web-app
  tag: "1.0.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hosts:
    - host: database-service
      paths: ["/"]

database:
  host: "database-service"
  port: "27017"
  name: "mydatabase"
